package com.xxl.kfapp.utils;

public class Urls {
    public static final String baseUrl = "http://106.15.61.209:7881/plazz/api";
//    public static final String baseUrl = "http://192.168.0.111:8090/plazz/api";
//    public static final String baseUrl = "https://qch.qchouses.com/plazz/api";
    public static final String login = "/authapi/login";
    public static final String reg = "/authapi/reg";
    public static final String getIdentifyingCode = "/authapi/getIdentifyingCode";
    public static final String forgotpass = "/authapi/forgotpass";

    public static final String getMemberAddrList = "/personalapi/getMemberAddrList";
    public static final String updateMemberAddress = "/personalapi/updateMemberAddress";
    public static final String deleteUserAddr = "/personalapi/deleteUserAddr";
    public static final String getMemberInfo = "/personalapi/getMemberInfo";
    public static final String updateMemberInfo = "/personalapi/updateMemberInfo";

    public static final String insertBarberApply = "/barberapi/insertBarberApply";
    public static final String getBarberApplyStatus = "/barberapi/getBarberApplyStatus";
    public static final String getBarberApplyInfo = "/barberapi/getBarberApplyInfo";
    public static final String getBarberGoodPic = "/barberapi/getBarberGoodPic";
    public static final String updateApplyStatus = "/barberapi/updateApplyStatus";
    public static final String getBarberQuestionList = "/barberapi/getBarberQuestionList";
    public static final String checkBarberTest = "/barberapi/checkBarberTest";
    public static final String getShopApplyStatus = "/barberapi/getShopApplyStatus";
    public static final String getShopApplyInfo = "/barberapi/getShopApplyInfo";
    public static final String updateShopApply = "/barberapi/updateShopApply";
    public static final String updateShopApplyStatus = "/authapi/updateShopApplyStatus";
    public static final String updateBarberCheckTicket = "/barberapi/updateBarberCheckTicket";
    public static final String getBarberTicketList = "/barberapi/getBarberTicketList";
    public static final String createUserOrder = "/barberapi/createUserOrder";
    public static final String getSelectAddrGoodPic = "/barberapi/getSelectAddrGoodPic";
    public static final String updateShopApplyInfo = "/barberapi/updateShopApplyInfo";
    public static final String getShopGoodsList = "/barberapi/getShopGoodsList";
    public static final String getAucteShopList = "/barberapi/getAucteShopList";
    public static final String updateShopApplyCancelSts = "/barberapi/updateShopApplyCancelSts";
    public static final String getSelectAddrStsInfo = "/barberapi/getSelectAddrStsInfo";
    public static final String getShopFeeList = "/barberapi/getShopFeeList";
    public static final String insertPriceRecord = "/barberapi/insertPriceRecord";
    public static final String updateShopViewCount = "/barberapi/updateShopViewCount";
    public static final String getBossCountInfo = "/barberapi/getBossCountInfo";
    public static final String getMemberTotalAmountInfo = "/barberapi/getMemberTotalAmountInfo";
    public static final String getMemberIncomeDetailList = "/barberapi/getMemberIncomeDetailList";
    public static final String getBossShopList = "/barberapi/getBossShopList";
    public static final String getBossShopDetailInfo = "/barberapi/getBossShopDetailInfo";
    public static final String updateShopInfo = "/barberapi/updateShopInfo";
    public static final String getShopModifyRecord = "/barberapi/getShopModifyRecord";
    public static final String getBossShopStaffList = "/barberapi/getBossShopStaffList";
    public static final String insertShopStaff = "/barberapi/insertShopStaff";
    public static final String getShopStaffSignList = "/barberapi/getShopStaffSignList";
    public static final String getShopCutRecord = "/barberapi/getShopCutRecord";
    public static final String updateShopPrice = "/barberapi/updateShopPrice";
    public static final String updateShopCxPrice = "/barberapi/updateShopCxPrice";
    public static final String getBarberCountInfo = "/barberapi/getBarberCountInfo";
    public static final String getBarberCutRecord = "/barberapi/getBarberCutRecord";
    public static final String getBarberSignInfo = "/barberapi/getBarberSignInfo";
    public static final String barberSign = "/barberapi/barberSign";
    public static final String getBarberSignUrlInfo = "/barberapi/getBarberSignUrlInfo";
    public static final String getMemberShopApply = "/barberapi/getMemberShopApply";
    public static final String getUserOrderList = "/barberapi/getUserOrderList";
    public static final String getUserNoticeList = "/barberapi/getUserNoticeList";
    public static final String updateUserNoticeReadSts = "/barberapi/updateUserNoticeReadSts";
    public static final String getUserTicketBackList = "/barberapi/getUserTicketBackList";
    public static final String getUserBackTicketDetailInfo = "/barberapi/getUserBackTicketDetailInfo";
    public static final String updateTicketBackInfo = "/barberapi/updateTicketBackInfo";
    public static final String getUserNoticeCount = "/barberapi/getUserNoticeCount";
    public static final String getShopBalanceList = "/barberapi/getShopBalanceList";
    public static final String getShopIncome = "/barberapi/getShopIncome";
    public static final String getShopCashApplyRecord = "/barberapi/getShopCashApplyRecord";
    public static final String getShopCashApplyInfo = "/barberapi/getShopCashApplyInfo";
    public static final String getAppConfig = "/barberapi/getAppConfig";
    public static final String insertShopCashApply = "/barberapi/insertShopCashApply";
    public static final String insertShopCloseApply = "/barberapi/insertShopCloseApply";
    public static final String getShopSetInfo = "/barberapi/getShopSetInfo";

    public static final String getDictList = "/commapi/getDictList";
    public static final String uploadForApp = "/file/uploadForApp";

    public static final String baseH5Url = "https://qch.qchouses.com/h5/article.php";
//    public static final String baseBidUrl = "https://qch.qchouses.com/h5/auction.php";
    public static final String baseBidUrl = "http://qchtest.qchouses.com/h5/auction.php";
    public static final String bidDepodit = "?artid=3";
    public static final String kfPromise = "?artid=2";
    public static final String bidH5 = "?shopid=";
    public static final String device = "https://qch.qchouses.com/h5/device.php?id=";
}
